name: LowkeycraftStats
version: 1.0.0
main: net.lowkeycraft.stats.LowkeycraftStats
author: Lowkeycraft Development Team
description: Real-time player statistics tracking plugin for Lowkeycraft servers
api-version: 1.20

commands:
  stats:
    description: View player statistics
    usage: /stats [player]
    permission: lowkeycraft.stats.view
    aliases: [statistics, playerstats]

  statsreload:
    description: Reload plugin configuration
    usage: /statsreload
    permission: lowkeycraft.stats.admin

permissions:
  lowkeycraft.stats.view:
    description: Allows viewing player statistics
    default: true

  lowkeycraft.stats.admin:
    description: Allows admin commands like reload
    default: op

  lowkeycraft.stats.*:
    description: All LowkeycraftStats permissions
    default: op
    children:
      - lowkeycraft.stats.view
      - lowkeycraft.stats.admin